In [97]:
# Basic slice syntax is i:j:k (start stop and step)
import numpy as np

x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x[1:7:2])


[1 3 5]


In [98]:
print(x[1:7])

[1 2 3 4 5 6]


In [99]:
# -i -j means n+i and n+j ( n is the number of elements ) -k means going backwards
print(x[-2:10])

[8 9]


In [100]:
print(x[-3:3:-1])

[7 6 5 4]


In [101]:
# default values: i not given default to 0, j to n, k to 1
print(x[1:])

[1 2 3 4 5 6 7 8 9]


In [102]:
# np.newaxis, like none, will create a new dimension
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x.shape

(2, 3, 1)

In [103]:
x[:, np.newaxis,:,:].shape

(2, 1, 3, 1)

In [104]:
print(x[:, np.newaxis,:,:])

[[[[1]
   [2]
   [3]]]


 [[[4]
   [5]
   [6]]]]


In [105]:
# Advanced indexing
# integer array indexing: index elements based on their index in the original array
# result[i_1, ..., i_M] == x[ind_1[i_1, ..., i_M], ind_2[i_1, ..., i_M],
#                           ..., ind_N[i_1, ..., i_M]]
x = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8],
              [9, 10, 11]])

rows = np.array([[0, 0],
                 [3, 3]])

cols = np.array([[0, 2],
                 [0, 2]])

print(x[rows, cols])

[[ 0  2]
 [ 9 11]]


In [106]:
rows = np.array([0, 3])
cols = np.array([0, 2])
rows[:, np.newaxis]


array([[0],
       [3]])

In [107]:
# Use broadcasting
print(x[rows[:, np.newaxis], cols])

[[ 0  2]
 [ 9 11]]


In [108]:
# Combining basic and advanced indexing
x[1:2, [0, 2]]

array([[3, 5]])

In [109]:
# Boolean array indexing
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x[~np.isnan(x)]

array([1., 2., 3.])

In [110]:
x = np.array([1., -1., -2., 3])
x[x < 0] += 20

In [111]:
print(x)

[ 1. 19. 18.  3.]


In [112]:
x = np.array([[0, 1], [1, 1], [2, 2]])
rowsum = x.sum(-1)
print(rowsum)

[1 2 4]


In [113]:
x[rowsum < 2, :]

array([[0, 1]])

In [114]:
# the boolean array should have the dimension it is expected to work with
rowsum = x.sum(-1, keepdims=True)

In [115]:
rowsum.shape

(3, 1)

In [116]:
print(rowsum)

[[1]
 [2]
 [4]]


In [117]:
print(rowsum < 2)

[[ True]
 [False]
 [False]]


In [123]:
print(rowsum <= 2)

[[ True]
 [ True]
 [False]]


In [ ]:
x = np.array([[ 0,  1,  2],
           [ 3,  4,  5],
           [ 6,  7,  8],
           [ 9, 10, 11]])

In [ ]:
rows = (x.sum(-1) % 2) == 0

In [ ]:
rows

In [ ]:
columns = [0, 2]

In [ ]:
x[np.ix_(rows, columns)]

In [ ]:
rows = rows.nonzero()[0]
print(rows)

In [ ]:
x[rows[:, np.newaxis], columns]